sudo: false
language: go
env:
- TRAVIS_BUILD_DIR="server-dev"
go:
- 1.10.x
before_deploy:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/tools/godep
- go get golang.org/x/sys/unix
- go get firebase.google.com/go
- go get google.golang.org/api/option
- go get github.com/stripe/stripe-go
- go get github.com/BurntSushi/toml
- godep save ./...' & godep save ./...
- heroku git:remote -a cavalry-app-travis
- heroku apps:destroy --app cavalry-app-travis --confirm cavalry-app-travis
- git init & git add . & heroku create cavalry-app-travis
- heroku git:remote -a cavalry-app-travis
- heroku config:set APP_ENV=dev

script:
- cd server-dev && set APP_ENV=dev & go run .
deploy:
  provider: heroku
  api_key:
    secure: kkpWuF4yafxwaAOwOvuDqu7/oZtwoiYN+Rd3z6JfJ1dJokZMNG/yRm6Fib/ZqOedyDJvfe6VG602koQUZAAZ4b0LnKv+jMnj1wZH9wb02LLF/SwvJmkEy59qelrM9VaBzsxAkEh6GTs5k7M9HYokfSEeAY4zrX9/+I+F3jVB4Wwn3m/RodIqplD3oft0PhsDL/i05f0ww5TOelxUZgdhI62xluLKLbU2Fm8CwgbTDynPc55I++C2mZcygUnia/L4/gmIMxq1MXSSsElmkMgV+zQgUNECMwpj0HrhyR6XNot1vv3oIlNYorv3kno7fG4n93iOM/W4ZcJCRi+3uWhE8ved10b5f7Z0DnImzfF3nWLU/NPTCEm/fdH+PVZSwgNMqFxAY+ybhv5EBbLHiLWPQ58OCo1QtnlFXt0n9NcNM7d/E1Ydkc8z0YgEOgSa29Y+WNAte4tTYkuPRBInOahUaeDoSJMDLFK0cCu3IEzEu5t/ojdrU0E8Hj/KK3hlQNAL0zzJiMS9Jem1TPtqclIeKa2h5oKlGr+xQiYhKERaHtK2HHUC+Un6qcxoVGWKeimOjf+9sJlmMH9Lq0S4ynvJIs5tPkSydkSlYo0kYfpCnNjIPI1vSv5Y79FMFjMWPlXfSv9gGM7rYMPGDk/EQonuwHw8ZNt3QdKRgrggVwxPJ0s=
  app: cavalry-app-travis
  on:
    repo: ncmd/cavalry
